matrix:
  include:
    - language: node_js
      node_js:
        - 10
      install: 
        - ./scripts/setup.sh
      script:
        - npm test
        
    - language: android
      dist: trusty
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - extra
      install: 
        - ./scripts/setup.sh
      before_script:
        - cd ./android
      script:
        - ./gradlew assembleDebug